version: '3'
services:
  cam:
    image: jheidel/cam
    ports:
      - "8080:80"
    volumes:
      # Mount location where videos are stored.
      - /home/jeff/db:/data/
      # Mount location where config.json is placed (derived from config.template.json)
      - /home/jeff/devconfig:/config/:ro
    environment:
      DATABASE: "root:root@(mysql)/cam"
      # NOTE: If you want to run SSL (which is needed for browser
      # notifications), define these environment variables and expose port 443.
      # Port 80 will act as a https redirect server.
      #   SSL_CERT: "/path/to/fullchain.pem"
      #   SSL_KEY: "/path/to/privkey.pem"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '10G'
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cam
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  db-data:
