version: '3'
services:
  cam:
    image: jheidel/cam
    ports:
      - "8443:8443"
    volumes:
      - /home/jeff/db:/mnt/db
      - /home/jeff/devkeys:/mnt/cert
      - /home/jeff/devconfig:/mnt/config
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '10G'
